name: Plugin
version: '${version}'
main: net.gze1206.plugin.Main
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10
permissions:
  plugin.admin:
    default: op
commands:
  money:
    description: 소지금 변경
    usage: "/<command> <username> <amount>"
    permission: plugin.admin
  title:
    description: 칭호 메뉴 열기
    usage: "/<command>"
    aliases:
      - 칭호
