name: NoruNexus
version: '${version}'
main: net.gze1206.noruNexus.Main
api-version: '1.20'
depend:
  - MythicMobs
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10
permissions:
  plugin.admin:
    default: op
commands:
  set-money:
    description: 소지금 변경
    usage: "/<command> <username> <amount>"
    permission: plugin.admin
  nnreload:
    description: 플러그인 설정 리로드
    usage: "/<command>"
    permission: plugin.admin
  칭호:
    description: 칭호 메뉴 열기
    usage: "/<command>"
    aliases:
      - title
  출금:
    description: 소지금을 아이템 형태로 꺼냅니다
    usage: "/<command> <amount>"
  상점:
    description: 어디서나 이용할 수 있는 상점 메뉴를 엽니다
    usage: "/<command>"
    aliases:
      - shop
  룬:
    description: 빈 룬에 문양을 각인하기 위한 메뉴를 엽니다
    usage: "/<command>"
    aliases:
      - rune
